<?php

return [

    // =============================================
    // FRENOS
    // =============================================
    1 => [
        'nombre' => 'Par Discos de Freno Ventilados',
        'icono' => 'fas fa-compact-disc',
        'precio' => '$2,144.00 MXN',
        'descripcion' => 'Par de discos de freno ventilados de alto rendimiento. Fabricados con hierro fundido de alta calidad para una disipacion de calor superior y frenado seguro.',
        'marca' => 'Brembo',
        'modelo' => 'DV-0921',
        'compatibilidad' => 'Volkswagen Bora, Jetta A6, Golf',
        'garantia' => '2 años o 40,000 km',
        'disponible' => true,
        'categoria' => 'Frenos',
    ],
    2 => [
        'nombre' => 'Balatas Ceramicas Delanteras',
        'icono' => 'fas fa-brake-warning',
        'precio' => '$644.00 MXN',
        'descripcion' => 'Balatas ceramicas de alta calidad con bajo nivel de ruido y polvo. Excelente rendimiento de frenado en condiciones secas y mojadas.',
        'marca' => 'Dynamik',
        'modelo' => 'BC-3310',
        'compatibilidad' => 'Chevrolet Sonic, Cruze, Trax',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Frenos',
    ],
    3 => [
        'nombre' => 'Bomba de Freno (Cilindro Maestro)',
        'icono' => 'fas fa-cogs',
        'precio' => '$1,210.00 MXN',
        'descripcion' => 'Cilindro maestro de freno de repuesto. Fabricado bajo estrictos estandares de calidad para garantizar presion de frenado constante y segura.',
        'marca' => 'TRW',
        'modelo' => 'BF-5520',
        'compatibilidad' => 'Jeep Compass, Cherokee, Renegade',
        'garantia' => '2 años o 30,000 km',
        'disponible' => true,
        'categoria' => 'Frenos',
    ],
    4 => [
        'nombre' => 'Kit de Balatas Semimetalicas',
        'icono' => 'fas fa-layer-group',
        'precio' => '$520.00 MXN',
        'descripcion' => 'Kit de pastillas de freno semimetalicas para uso rudo. Alta durabilidad y resistencia al desgaste, ideales para conduccion urbana y carretera.',
        'marca' => 'Partech',
        'modelo' => 'SM-7845',
        'compatibilidad' => 'Nissan Versa, March, Note',
        'garantia' => '1 año o 15,000 km',
        'disponible' => true,
        'categoria' => 'Frenos',
    ],
    5 => [
        'nombre' => 'Caliper de Freno Delantero',
        'icono' => 'fas fa-toolbox',
        'precio' => '$1,850.00 MXN',
        'descripcion' => 'Mordaza de freno delantera reconstruida con piston nuevo. Incluye sellos y accesorios de montaje. Ajuste directo sin modificaciones.',
        'marca' => 'Brembo',
        'modelo' => 'CP-1240',
        'compatibilidad' => 'Honda Civic, CR-V, Accord',
        'garantia' => '2 años o 40,000 km',
        'disponible' => true,
        'categoria' => 'Frenos',
    ],
    6 => [
        'nombre' => 'Tambor de Freno Trasero',
        'icono' => 'fas fa-drum',
        'precio' => '$680.00 MXN',
        'descripcion' => 'Tambor de freno trasero de hierro fundido gris. Superficie de frenado rectificada de fabrica para un asentamiento optimo de las balatas.',
        'marca' => 'Dynamik',
        'modelo' => 'TB-3320',
        'compatibilidad' => 'Chevrolet Aveo, Spark, Beat',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Frenos',
    ],
    7 => [
        'nombre' => 'Manguera de Frenos Delantera',
        'icono' => 'fas fa-grip-lines',
        'precio' => '$285.00 MXN',
        'descripcion' => 'Manguera flexible de frenos con refuerzo interno de malla. Resistente a la presion y a los fluidos de freno DOT 3 y DOT 4.',
        'marca' => 'TRW',
        'modelo' => 'MF-0115',
        'compatibilidad' => 'Volkswagen Jetta A4, Golf A4, Derby',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Frenos',
    ],
    8 => [
        'nombre' => 'Booster de Frenos',
        'icono' => 'fas fa-circle-notch',
        'precio' => '$2,350.00 MXN',
        'descripcion' => 'Servofreno (booster) de vacio. Amplifica la fuerza de frenado para un pedal mas suave y una respuesta de frenado mas eficiente.',
        'marca' => 'Partech',
        'modelo' => 'BS-4410',
        'compatibilidad' => 'Ford Focus, Fiesta, EcoSport',
        'garantia' => '2 años',
        'disponible' => false,
        'categoria' => 'Frenos',
    ],

    // =============================================
    // SUSPENSION Y DIRECCION
    // =============================================
    9 => [
        'nombre' => 'Amortiguador Delantero a Gas',
        'icono' => 'fas fa-arrows-alt-v',
        'precio' => '$1,250.00 MXN',
        'descripcion' => 'Amortiguador delantero de gas presurizado para mayor estabilidad y control. Tecnologia de valvula sensible a la velocidad para un manejo superior.',
        'marca' => 'Monroe',
        'modelo' => 'AG-4521',
        'compatibilidad' => 'Nissan Tsuru, Chevrolet Aveo, VW Jetta A4',
        'garantia' => '2 años o 40,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    10 => [
        'nombre' => 'Amortiguador Trasero Hidraulico',
        'icono' => 'fas fa-arrows-alt-v',
        'precio' => '$890.00 MXN',
        'descripcion' => 'Amortiguador trasero hidraulico de doble accion. Proporciona un viaje suave y confortable absorbiendo las irregularidades del camino.',
        'marca' => 'Boge',
        'modelo' => 'AH-2283',
        'compatibilidad' => 'Toyota Corolla, Yaris, Avanza',
        'garantia' => '2 años o 40,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    11 => [
        'nombre' => 'Base de Amortiguador Delantera',
        'icono' => 'fas fa-dot-circle',
        'precio' => '$450.00 MXN',
        'descripcion' => 'Base de montaje para amortiguador delantero con balero incluido. Reduce vibraciones y ruidos transmitidos a la carroceria del vehiculo.',
        'marca' => 'Master Ride',
        'modelo' => 'BA-1150',
        'compatibilidad' => 'Chevrolet Aveo, Spark, Beat',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    12 => [
        'nombre' => 'Terminal de Direccion Exterior',
        'icono' => 'fas fa-link',
        'precio' => '$320.00 MXN',
        'descripcion' => 'Terminal de direccion (rotula exterior) con junta esferica sellada. Fabricada en acero forjado para maxima resistencia y durabilidad.',
        'marca' => 'SYD',
        'modelo' => 'TD-0878',
        'compatibilidad' => 'Nissan Sentra, Versa, Tiida',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    13 => [
        'nombre' => 'Horquilla de Suspension Inferior',
        'icono' => 'fas fa-code-branch',
        'precio' => '$1,680.00 MXN',
        'descripcion' => 'Brazo de control inferior (horquilla) con bujes y rotula premontados. Estructura de aluminio forjado ligera y resistente.',
        'marca' => 'TRW',
        'modelo' => 'HS-3350',
        'compatibilidad' => 'Volkswagen Jetta A6, Bora, Golf',
        'garantia' => '2 años o 40,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    14 => [
        'nombre' => 'Cremallera de Direccion',
        'icono' => 'fas fa-steering-wheel',
        'precio' => '$4,500.00 MXN',
        'descripcion' => 'Cremallera de direccion hidraulica reconstruida. Incluye terminales interiores y sellos nuevos. Prueba de presion y estanqueidad garantizada.',
        'marca' => 'GROB',
        'modelo' => 'CR-2240',
        'compatibilidad' => 'Honda Civic 2006-2011, CR-V',
        'garantia' => '1 año o 20,000 km',
        'disponible' => false,
        'categoria' => 'Suspension y Direccion',
    ],
    15 => [
        'nombre' => 'Maza de Rueda Delantera',
        'icono' => 'fas fa-circle',
        'precio' => '$1,350.00 MXN',
        'descripcion' => 'Conjunto de maza y balero de rueda delantera con sensor ABS integrado. Instalacion directa sin necesidad de prensado.',
        'marca' => 'SYD',
        'modelo' => 'MR-5520',
        'compatibilidad' => 'Ford Focus, Escape, Fusion',
        'garantia' => '2 años o 40,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    16 => [
        'nombre' => 'Rotula de Suspension Superior',
        'icono' => 'fas fa-dot-circle',
        'precio' => '$380.00 MXN',
        'descripcion' => 'Rotula de suspension superior con guardapolvo integrado. Junta esferica de precision para un manejo seguro y alineacion correcta.',
        'marca' => 'Master Ride',
        'modelo' => 'RS-0742',
        'compatibilidad' => 'Nissan Frontier, NP300, Pathfinder',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    17 => [
        'nombre' => 'Resorte de Suspension Delantero',
        'icono' => 'fas fa-compress-alt',
        'precio' => '$750.00 MXN',
        'descripcion' => 'Resorte helicoidal de suspension delantera. Fabricado en acero de alta resistencia con recubrimiento epoxico anticorrosion.',
        'marca' => 'Monroe',
        'modelo' => 'RD-1122',
        'compatibilidad' => 'Chevrolet Cruze, Sonic, Trax',
        'garantia' => '2 años',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    18 => [
        'nombre' => 'Bieleta Estabilizadora',
        'icono' => 'fas fa-link',
        'precio' => '$190.00 MXN',
        'descripcion' => 'Bieleta (tirante) de barra estabilizadora con rotulas en ambos extremos. Elimina ruidos y mejora la estabilidad en curvas.',
        'marca' => 'SYD',
        'modelo' => 'BE-0350',
        'compatibilidad' => 'Toyota Corolla, Camry, RAV4',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],
    19 => [
        'nombre' => 'Bomba de Direccion Hidraulica',
        'icono' => 'fas fa-tachometer-alt',
        'precio' => '$2,800.00 MXN',
        'descripcion' => 'Bomba de direccion hidraulica de paletas con deposito incluido. Proporciona asistencia de direccion suave y consistente a todas las velocidades.',
        'marca' => 'TRW',
        'modelo' => 'BDH-1180',
        'compatibilidad' => 'Chevrolet Silverado, Suburban, Tahoe',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Suspension y Direccion',
    ],

    // =============================================
    // ILUMINACION
    // =============================================
    20 => [
        'nombre' => 'Faro Delantero Derecho',
        'icono' => 'fas fa-lightbulb',
        'precio' => '$1,890.00 MXN',
        'descripcion' => 'Faro delantero lado pasajero con lente transparente. Compatible con focos halogenos H4. Incluye base, arneses y ajustadores.',
        'marca' => 'TYC',
        'modelo' => 'FD-2240',
        'compatibilidad' => 'Nissan NP300 2016-2023',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],
    21 => [
        'nombre' => 'Faro Delantero Izquierdo',
        'icono' => 'fas fa-lightbulb',
        'precio' => '$1,890.00 MXN',
        'descripcion' => 'Faro delantero lado conductor con lente transparente. Ajuste directo, misma calidad que equipo original. Incluye sistema de ajuste de altura.',
        'marca' => 'TYC',
        'modelo' => 'FD-2241',
        'compatibilidad' => 'Nissan NP300 2016-2023',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],
    22 => [
        'nombre' => 'Calavera Trasera LED',
        'icono' => 'fas fa-sun',
        'precio' => '$2,350.00 MXN',
        'descripcion' => 'Calavera trasera con tecnologia LED integrada. Mayor visibilidad y menor consumo energetico. Diseño tipo ahumado deportivo.',
        'marca' => 'DEPO',
        'modelo' => 'CL-5510',
        'compatibilidad' => 'Volkswagen Jetta A6 2011-2018',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],
    23 => [
        'nombre' => 'Faro para Niebla Delantero',
        'icono' => 'fas fa-cloud-sun',
        'precio' => '$780.00 MXN',
        'descripcion' => 'Faro auxiliar antiniebla con lente transparente y reflector cromado. Patron de haz ancho y bajo para mejorar visibilidad en condiciones adversas.',
        'marca' => 'TYC',
        'modelo' => 'FN-1180',
        'compatibilidad' => 'Toyota Corolla 2014-2019, Yaris',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],
    24 => [
        'nombre' => 'Kit de Focos LED H7',
        'icono' => 'fas fa-bolt',
        'precio' => '$950.00 MXN',
        'descripcion' => 'Par de focos LED H7 de 6000K (luz blanca). 12,000 lumenes por par con ventilador de enfriamiento integrado. Plug and play sin modificaciones.',
        'marca' => 'DEPO',
        'modelo' => 'LED-H7',
        'compatibilidad' => 'Universal - Vehiculos con socket H7',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],
    25 => [
        'nombre' => 'Barra LED 120W 22 Pulgadas',
        'icono' => 'fas fa-grip-horizontal',
        'precio' => '$3,200.00 MXN',
        'descripcion' => 'Barra de luz LED de alto rendimiento con 40 LEDs CREE. Combinacion de haz spot y flood para iluminacion de largo y corto alcance. IP68.',
        'marca' => 'TYC',
        'modelo' => 'BL-22120',
        'compatibilidad' => 'Universal - Camionetas y vehiculos todo terreno',
        'garantia' => '2 años',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],
    26 => [
        'nombre' => 'Foco Halogeno H4 60/55W',
        'icono' => 'fas fa-lightbulb',
        'precio' => '$120.00 MXN',
        'descripcion' => 'Foco halogeno estandar H4 de doble filamento para luz alta y baja. Luz amarilla calida 3200K. Larga vida util de 500 horas.',
        'marca' => 'TYC',
        'modelo' => 'FH-H4',
        'compatibilidad' => 'Universal - Vehiculos con socket H4',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],
    27 => [
        'nombre' => 'Cuarto Lateral Ambar',
        'icono' => 'fas fa-square',
        'precio' => '$180.00 MXN',
        'descripcion' => 'Luz de cuarto lateral color ambar. Indica la posicion del vehiculo a otros conductores. Incluye base y foco.',
        'marca' => 'DEPO',
        'modelo' => 'CL-0410',
        'compatibilidad' => 'Chevrolet Silverado 2007-2013',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Iluminacion',
    ],

    // =============================================
    // CARROCERIA Y COLISION
    // =============================================
    28 => [
        'nombre' => 'Defensa Delantera Completa',
        'icono' => 'fas fa-car',
        'precio' => '$3,630.00 MXN',
        'descripcion' => 'Fascia delantera de plastico ABS inyectado. Acabado en color negro liso para pintar. Incluye refuerzos internos y puntos de montaje.',
        'marca' => 'Generica',
        'modelo' => 'DD-NP300',
        'compatibilidad' => 'Nissan NP300 2021-2023',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    29 => [
        'nombre' => 'Espejo Electrico con Desempañante',
        'icono' => 'fas fa-clone',
        'precio' => '$1,326.00 MXN',
        'descripcion' => 'Espejo retrovisor electrico con funcion de desempañante y luz de cortesia. Acabado para pintar. Lado conductor.',
        'marca' => 'Generica',
        'modelo' => 'EE-FUS',
        'compatibilidad' => 'Ford Fusion 2006-2012',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    30 => [
        'nombre' => 'Cofre (Capo) Delantero',
        'icono' => 'fas fa-car-side',
        'precio' => '$4,200.00 MXN',
        'descripcion' => 'Cofre delantero de lamina de acero calibre 20. Incluye refuerzos estructurales y puntos de bisagra. Acabado en primer gris.',
        'marca' => 'Generica',
        'modelo' => 'CF-SEN',
        'compatibilidad' => 'Nissan Sentra 2013-2019',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    31 => [
        'nombre' => 'Parrilla Frontal Cromada',
        'icono' => 'fas fa-th',
        'precio' => '$1,450.00 MXN',
        'descripcion' => 'Parrilla frontal con acabado cromado y detalle en negro brillante. Diseño OEM para ajuste perfecto. Incluye emblema y accesorios de montaje.',
        'marca' => 'Generica',
        'modelo' => 'PF-JET6',
        'compatibilidad' => 'Volkswagen Jetta A6 2015-2018',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    32 => [
        'nombre' => 'Tolva Salpicadera Delantera',
        'icono' => 'fas fa-shield-alt',
        'precio' => '$380.00 MXN',
        'descripcion' => 'Tolva guardabarros interna de plastico. Protege los componentes del motor contra agua, lodo y piedras. Instalacion con grapas y tornillos.',
        'marca' => 'Generica',
        'modelo' => 'TS-AVE',
        'compatibilidad' => 'Chevrolet Aveo 2012-2018',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    33 => [
        'nombre' => 'Salpicadera Delantera Derecha',
        'icono' => 'fas fa-shield-alt',
        'precio' => '$1,950.00 MXN',
        'descripcion' => 'Salpicadera delantera lado pasajero de lamina de acero. Incluye soporte de faro y arco de rueda. Acabado en primer anticorrosivo.',
        'marca' => 'Generica',
        'modelo' => 'SD-CIV',
        'compatibilidad' => 'Honda Civic 2016-2021',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    34 => [
        'nombre' => 'Manija Puerta Exterior Cromada',
        'icono' => 'fas fa-door-open',
        'precio' => '$350.00 MXN',
        'descripcion' => 'Manija exterior para puerta delantera con acabado cromado. Mecanismo de apertura resistente, incluye cilindro para llave.',
        'marca' => 'Generica',
        'modelo' => 'MP-CIT',
        'compatibilidad' => 'Honda City 2015-2020',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    35 => [
        'nombre' => 'Plumas Limpiaparabrisas (Par)',
        'icono' => 'fas fa-wind',
        'precio' => '$425.00 MXN',
        'descripcion' => 'Par de plumas limpiaparabrisas tipo bayoneta con hule de silicone. Limpieza silenciosa y eficiente. Diseño aerodinamico de perfil bajo.',
        'marca' => 'Gonher',
        'modelo' => 'PL-SIL',
        'compatibilidad' => 'Chevrolet Silverado 2000-2020',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],
    36 => [
        'nombre' => 'Spoiler Trasero de Cajuela',
        'icono' => 'fas fa-angle-up',
        'precio' => '$1,200.00 MXN',
        'descripcion' => 'Aleron trasero tipo lip de plastico ABS. Se adhiere con cinta 3M y tornillos de refuerzo. Acabado en primer listo para pintar.',
        'marca' => 'Generica',
        'modelo' => 'SP-UNI',
        'compatibilidad' => 'Universal sedanes medianos',
        'garantia' => '6 meses',
        'disponible' => true,
        'categoria' => 'Carroceria y Colision',
    ],

    // =============================================
    // LLANTAS
    // =============================================
    37 => [
        'nombre' => 'Llanta 185/65 R15 All Season',
        'icono' => 'fas fa-circle-notch',
        'precio' => '$1,450.00 MXN',
        'descripcion' => 'Llanta para auto sedan toda temporada. Compuesto de hule con silice para mejor agarre en mojado. Diseño de banda de rodamiento optimizado.',
        'marca' => 'Goodyear',
        'modelo' => 'Assurance',
        'compatibilidad' => 'VW Jetta, Nissan Sentra, Honda Civic',
        'garantia' => '5 años o 80,000 km',
        'disponible' => true,
        'categoria' => 'Llantas',
    ],
    38 => [
        'nombre' => 'Llanta 205/55 R16 Performance',
        'icono' => 'fas fa-circle-notch',
        'precio' => '$2,100.00 MXN',
        'descripcion' => 'Llanta de alto rendimiento con perfil bajo para vehiculos deportivos y sedanes premium. Excelente traccion lateral en curvas.',
        'marca' => 'Continental',
        'modelo' => 'ContiPremium',
        'compatibilidad' => 'Mazda 3, Toyota Corolla, VW Golf',
        'garantia' => '5 años o 60,000 km',
        'disponible' => true,
        'categoria' => 'Llantas',
    ],
    39 => [
        'nombre' => 'Llanta 235/75 R15 Todo Terreno',
        'icono' => 'fas fa-circle-notch',
        'precio' => '$2,800.00 MXN',
        'descripcion' => 'Llanta todo terreno AT con diseño de taco agresivo. Refuerzo lateral contra impactos. Ideal para camionetas de trabajo y aventura.',
        'marca' => 'Cooper',
        'modelo' => 'Discoverer AT3',
        'compatibilidad' => 'Nissan NP300, Ford Ranger, Toyota Hilux',
        'garantia' => '5 años o 60,000 km',
        'disponible' => true,
        'categoria' => 'Llantas',
    ],
    40 => [
        'nombre' => 'Llanta 265/70 R17 Highway',
        'icono' => 'fas fa-circle-notch',
        'precio' => '$3,400.00 MXN',
        'descripcion' => 'Llanta para camioneta SUV de uso en carretera. Rodamiento silencioso con alto kilometraje. Canales de evacuacion de agua amplios.',
        'marca' => 'Yokohama',
        'modelo' => 'Geolandar HT',
        'compatibilidad' => 'Chevrolet Silverado, Suburban, Tahoe',
        'garantia' => '5 años o 80,000 km',
        'disponible' => true,
        'categoria' => 'Llantas',
    ],
    41 => [
        'nombre' => 'Llanta 175/70 R13 Economica',
        'icono' => 'fas fa-circle-notch',
        'precio' => '$850.00 MXN',
        'descripcion' => 'Llanta economica para autos compactos. Baja resistencia al rodamiento para ahorro de combustible. Buena duracion en uso urbano.',
        'marca' => 'Tornel',
        'modelo' => 'Real',
        'compatibilidad' => 'Nissan Tsuru, Chevy, VW Sedan',
        'garantia' => '3 años o 40,000 km',
        'disponible' => true,
        'categoria' => 'Llantas',
    ],
    42 => [
        'nombre' => 'Llanta 225/45 R18 UHP',
        'icono' => 'fas fa-circle-notch',
        'precio' => '$3,950.00 MXN',
        'descripcion' => 'Llanta ultra alto rendimiento para vehiculos deportivos. Compuesto de carrera para maximo agarre. Clasificacion de velocidad W (270 km/h).',
        'marca' => 'Nexen',
        'modelo' => 'N Fera SU1',
        'compatibilidad' => 'BMW Serie 3, Audi A4, Mercedes C-Class',
        'garantia' => '5 años o 50,000 km',
        'disponible' => true,
        'categoria' => 'Llantas',
    ],

    // =============================================
    // KITS DE AFINACION
    // =============================================
    43 => [
        'nombre' => 'Kit de Afinacion Completo',
        'icono' => 'fas fa-wrench',
        'precio' => '$1,850.00 MXN',
        'descripcion' => 'Kit de afinacion mayor que incluye: filtro de aceite, filtro de aire, filtro de gasolina, bujias de platino y aceite sintetico 5W-30 (5 litros).',
        'marca' => 'Gonher / Motorcraft',
        'modelo' => 'KAC-4CIL',
        'compatibilidad' => 'Ford Fiesta 1.6L 2011-2019',
        'garantia' => '6 meses o 10,000 km',
        'disponible' => true,
        'categoria' => 'Kits de Afinacion',
    ],
    44 => [
        'nombre' => 'Kit de Aceite y Filtro de Motor',
        'icono' => 'fas fa-oil-can',
        'precio' => '$890.00 MXN',
        'descripcion' => 'Kit de cambio de aceite que incluye: 4 litros de aceite sintetico 5W-30 y filtro de aceite premium. Todo lo necesario para un cambio rapido.',
        'marca' => 'Mobil / Gonher',
        'modelo' => 'KAF-SIN',
        'compatibilidad' => 'Motores 4 cilindros de hasta 2.0L',
        'garantia' => '6 meses o 10,000 km',
        'disponible' => true,
        'categoria' => 'Kits de Afinacion',
    ],
    45 => [
        'nombre' => 'Kit de Filtros (Aire + Aceite + Gasolina)',
        'icono' => 'fas fa-filter',
        'precio' => '$520.00 MXN',
        'descripcion' => 'Set de 3 filtros para afinacion: filtro de aire del motor, filtro de aceite y filtro de combustible. Materiales filtrantes de alta eficiencia.',
        'marca' => 'Gonher',
        'modelo' => 'KF-3PZ',
        'compatibilidad' => 'Chevrolet Aveo 1.6L 2012-2018',
        'garantia' => '6 meses o 10,000 km',
        'disponible' => true,
        'categoria' => 'Kits de Afinacion',
    ],
    46 => [
        'nombre' => 'Kit de Filtros y Bujias',
        'icono' => 'fas fa-plug',
        'precio' => '$780.00 MXN',
        'descripcion' => 'Incluye filtro de aire, filtro de aceite, 4 bujias de iridio y junta de tapon de carter. Ideal para afinaciones economicas sin aceite.',
        'marca' => 'NGK / Gonher',
        'modelo' => 'KFB-IR4',
        'compatibilidad' => 'Nissan Versa 1.6L 2012-2020',
        'garantia' => '6 meses o 10,000 km',
        'disponible' => true,
        'categoria' => 'Kits de Afinacion',
    ],
    47 => [
        'nombre' => 'Aceite de Motor Sintetico 5W-30 (5L)',
        'icono' => 'fas fa-oil-can',
        'precio' => '$650.00 MXN',
        'descripcion' => 'Aceite sintetico completo 5W-30 de 5 litros. Proteccion superior del motor contra el desgaste, depositos y lodos. Cumple normas API SP.',
        'marca' => 'Mobil',
        'modelo' => 'Super Synthetic',
        'compatibilidad' => 'Universal - Motores a gasolina',
        'garantia' => 'N/A - Producto de consumo',
        'disponible' => true,
        'categoria' => 'Kits de Afinacion',
    ],
    48 => [
        'nombre' => 'Bujia de Encendido Iridio',
        'icono' => 'fas fa-bolt',
        'precio' => '$185.00 MXN',
        'descripcion' => 'Bujia de encendido con electrodo central de iridio fino (0.6mm). Encendido mas rapido, combustion mas completa y mayor vida util (100,000 km).',
        'marca' => 'NGK',
        'modelo' => 'Iridium IX',
        'compatibilidad' => 'Universal - Consultar aplicacion por vehiculo',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Kits de Afinacion',
    ],

    // =============================================
    // SENSORES Y ELECTRICO
    // =============================================
    49 => [
        'nombre' => 'Sensor de Oxigeno (Lambda)',
        'icono' => 'fas fa-microchip',
        'precio' => '$680.00 MXN',
        'descripcion' => 'Sensor de oxigeno de banda ancha para control de mezcla aire-combustible. Conector OEM de 4 cables. Tiempo de respuesta rapido.',
        'marca' => 'NTK',
        'modelo' => 'SO-4WB',
        'compatibilidad' => 'Nissan Sentra, Versa, March 2013-2020',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],
    50 => [
        'nombre' => 'Sensor de Posicion del Cigüeñal (CKP)',
        'icono' => 'fas fa-satellite-dish',
        'precio' => '$520.00 MXN',
        'descripcion' => 'Sensor CKP de efecto Hall para señal de RPM y posicion del cigüeñal. Esencial para el encendido y la inyeccion de combustible.',
        'marca' => 'NTK',
        'modelo' => 'CKP-2240',
        'compatibilidad' => 'Chevrolet Aveo, Cruze, Sonic 2012-2018',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],
    51 => [
        'nombre' => 'Sensor MAF (Flujo de Aire)',
        'icono' => 'fas fa-wind',
        'precio' => '$1,250.00 MXN',
        'descripcion' => 'Sensor de masa de flujo de aire con elemento sensor de hilo caliente. Medicion precisa del volumen de aire que ingresa al motor.',
        'marca' => 'Bosch',
        'modelo' => 'MAF-5521',
        'compatibilidad' => 'Volkswagen Jetta A4, Golf A4, Bora',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],
    52 => [
        'nombre' => 'Alternador Remanufacturado 120A',
        'icono' => 'fas fa-car-battery',
        'precio' => '$2,400.00 MXN',
        'descripcion' => 'Alternador reconstruido con regulador de voltaje y escobillas nuevos. Potencia de 120 Amperes. Probado en banco para garantizar rendimiento.',
        'marca' => 'Bosch',
        'modelo' => 'ALT-120R',
        'compatibilidad' => 'Ford Focus, Fiesta, EcoSport 2012-2019',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],
    53 => [
        'nombre' => 'Marcha (Motor de Arranque)',
        'icono' => 'fas fa-play-circle',
        'precio' => '$1,950.00 MXN',
        'descripcion' => 'Motor de arranque remanufacturado con solenoide y bendix nuevos. Giro suave y potente para arranque confiable en frio.',
        'marca' => 'Bosch',
        'modelo' => 'MA-1400',
        'compatibilidad' => 'Nissan Sentra, Tiida, Versa 2007-2019',
        'garantia' => '1 año o 20,000 km',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],
    54 => [
        'nombre' => 'Sensor de Temperatura del Refrigerante',
        'icono' => 'fas fa-thermometer-half',
        'precio' => '$220.00 MXN',
        'descripcion' => 'Sensor ECT de tipo termistor NTC. Envia señal de temperatura del motor a la computadora para control de inyeccion y ventilador.',
        'marca' => 'NTK',
        'modelo' => 'ECT-0335',
        'compatibilidad' => 'Chevrolet Spark, Beat, Aveo 2011-2018',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],
    55 => [
        'nombre' => 'Bobina de Encendido',
        'icono' => 'fas fa-bolt',
        'precio' => '$480.00 MXN',
        'descripcion' => 'Bobina de encendido tipo lapiz (COP) con modulo de potencia integrado. Genera chispa de alto voltaje para combustion eficiente.',
        'marca' => 'Bosch',
        'modelo' => 'BE-COP4',
        'compatibilidad' => 'Volkswagen Jetta A6, Golf, Tiguan 2.0 TSI',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],
    56 => [
        'nombre' => 'Sensor de Velocidad (VSS)',
        'icono' => 'fas fa-tachometer-alt',
        'precio' => '$350.00 MXN',
        'descripcion' => 'Sensor de velocidad del vehiculo tipo magnetoresistivo. Señal digital precisa para velocimetro, ABS y control de transmision.',
        'marca' => 'NTK',
        'modelo' => 'VSS-2210',
        'compatibilidad' => 'Toyota Corolla, Yaris, Hilux 2010-2020',
        'garantia' => '1 año',
        'disponible' => true,
        'categoria' => 'Sensores y Electrico',
    ],

    // =============================================
    // ACEITES Y ADITIVOS
    // =============================================
    57 => [
        'nombre' => 'Aceite de Motor Sintetico 0W-20 (4L)',
        'icono' => 'fas fa-oil-can',
        'precio' => '$720.00 MXN',
        'descripcion' => 'Aceite sintetico de baja viscosidad 0W-20 para motores modernos. Ahorro de combustible y proteccion desde el arranque en frio. API SP.',
        'marca' => 'Castrol',
        'modelo' => 'Edge 0W-20',
        'compatibilidad' => 'Motores Honda, Toyota, Mazda, Hyundai',
        'garantia' => 'N/A - Producto de consumo',
        'disponible' => true,
        'categoria' => 'Aceites y Aditivos',
    ],
    58 => [
        'nombre' => 'Aceite de Transmision Automatica ATF',
        'icono' => 'fas fa-tint',
        'precio' => '$280.00 MXN',
        'descripcion' => 'Fluido para transmision automatica multiusos. Compatible con la mayoria de transmisiones de 4, 5 y 6 velocidades. Proteccion antidesgaste.',
        'marca' => 'Mobil',
        'modelo' => 'ATF Multi',
        'compatibilidad' => 'Transmisiones automaticas convencionales',
        'garantia' => 'N/A - Producto de consumo',
        'disponible' => true,
        'categoria' => 'Aceites y Aditivos',
    ],
    59 => [
        'nombre' => 'Refrigerante Anticongelante (4L)',
        'icono' => 'fas fa-snowflake',
        'precio' => '$250.00 MXN',
        'descripcion' => 'Refrigerante de larga vida 50/50 premezclado. Proteccion contra congelamiento hasta -37 grados C y ebullicion hasta 129 grados C. Compatible con todos los metales.',
        'marca' => 'Peak',
        'modelo' => 'Long Life',
        'compatibilidad' => 'Universal - Todos los vehiculos',
        'garantia' => 'N/A - Producto de consumo',
        'disponible' => true,
        'categoria' => 'Aceites y Aditivos',
    ],
    60 => [
        'nombre' => 'Liquido de Frenos DOT 4 (500ml)',
        'icono' => 'fas fa-flask',
        'precio' => '$120.00 MXN',
        'descripcion' => 'Fluido de frenos DOT 4 de alto punto de ebullicion (230 grados C seco). Compatible con sistemas ABS. No mezclar con DOT 5 (base silicone).',
        'marca' => 'TRW',
        'modelo' => 'DOT4-500',
        'compatibilidad' => 'Universal - Sistemas de frenos DOT 3/4',
        'garantia' => 'N/A - Producto de consumo',
        'disponible' => true,
        'categoria' => 'Aceites y Aditivos',
    ],
    61 => [
        'nombre' => 'Aceite de Direccion Hidraulica',
        'icono' => 'fas fa-tint',
        'precio' => '$150.00 MXN',
        'descripcion' => 'Fluido ATF para sistemas de direccion hidraulica. Formulado con aditivos antidesgaste y antiespumante para una direccion suave.',
        'marca' => 'Bardahl',
        'modelo' => 'PSF-ATF',
        'compatibilidad' => 'Vehiculos con direccion hidraulica',
        'garantia' => 'N/A - Producto de consumo',
        'disponible' => true,
        'categoria' => 'Aceites y Aditivos',
    ],
    62 => [
        'nombre' => 'Aditivo Limpia Inyectores',
        'icono' => 'fas fa-spray-can',
        'precio' => '$180.00 MXN',
        'descripcion' => 'Aditivo concentrado para limpieza del sistema de inyeccion de combustible. Elimina depositos de carbon y restaura el patron de rocio.',
        'marca' => 'Bardahl',
        'modelo' => 'Top Fuel',
        'compatibilidad' => 'Motores a gasolina con inyeccion electronica',
        'garantia' => 'N/A - Producto de consumo',
        'disponible' => true,
        'categoria' => 'Aceites y Aditivos',
    ],

];
